name: CI
on:
  push:
      branches:
      - main
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb mesa-utils mesa-vulkan-drivers dbus
      - name: Start Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          eval $(dbus-launch)
          export DBUS_SESSION_BUS_ADDRESS
          export DBUS_SESSION_BUS_PID
      - name: Checkout
        uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: x64
      - uses: julia-actions/cache@v1
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
             julia --project=. test/dashboard_options.jl --bench"
      
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using ERPExplorer
            DocMeta.setdocmeta!(ERPExplorer, :DocTestSetup, :(using ERPExplorer); recursive=true)
            doctest(ERPExplorer)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
